apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: job1
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: helloworld
  namespace: job1
  labels:
    scaler.keda: "true"
spec:
  jobTargetRef:
    template:
      spec:
        restartPolicy: Never
        containers:
          - name: helloworld
            image: busybox:latest
            command:
              - sleep
              - "30"
    backoffLimit: 1
    ttlSecondsAfterFinished: 60
  pollingInterval: 15
  minReplicaCount: 0
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: http://noc.opsworks.co:8080/scaler/
        valueLocation: "job1"
